### ISSUE TITLE
Update ISSS and Study Abroad Maps

### ISSUE THREAD

**Issue by joewhitsitt** [ITS-UofIowa/international.uiowa.edu#20]
https://international.uiowa.edu/about/stats/study-abroad/map
https://international.uiowa.edu/about/stats/isss/map

Currently, the data for these maps is hardcoded. In the past, there was talk about making this more editor friendly.

Previously Amy Brewster and Liz Wildenberg De Hernandez provided updated data in the attached spreadsheet.
[webmap 13-14.xlsx](https://github.com/ITS-UofIowa/international.uiowa.edu/files/1045488/webmap.13-14.xlsx)

**Comment by marleen-linares** [comment]
Hi Joe, 
I've attached the most recent data for international students for the map on the page below. Let me know if you need anything else from me.
https://international.uiowa.edu/about/stats/isss/map
[webmap.15-16.xlsx](https://github.com/ITS-UofIowa/international.uiowa.edu/files/1061579/webmap.15-16.xlsx)

**Comment by joewhitsitt** [comment]
@marleen-linares 
I have updated the file and pushed to DEV, however Google is caching the data pretty intensely and is still showing the old numbers. Normally this is a good thing as the data doesn't change too often. I will check back tomorrow morning to see if the map updates before pushing this to PROD.

Did you have about/stats/study-abroad/map data as well?

**Comment by marleen-linares** [comment]
Sounds good, thanks Joe. We don't have the study abroad numbers yet but I will forward them on as soon as we do.

**Comment by joewhitsitt** [comment]
I added a cache breaking string to the end of the data file url to tell Google to fetch a new copy. This will happen daily. Pushing this to PROD.
