### ISSUE TITLE
Footer Addition

### ISSUE THREAD

**Issue by marleen-linares** [ITS-UofIowa/international.uiowa.edu#23]
Hi Joe, 

Hope you're having a great summer. I got a request from my supervisor to add the attached badge to the footer. Would this be an easy add? I envision it going under the social media icons but I'm open to any suggestions you may have. 

Thanks, 
Marleen 
![simon](https://user-images.githubusercontent.com/29282775/29031965-82fbf978-7b55-11e7-91f0-85d5595e6e41.png)

**Comment by joewhitsitt** [comment]
Sadly, projects are keeping me busy right now. See https://international.dev.drupal.uiowa.edu for a mockup. This is the best I can do without writing specific styles for it which take more time. If this works for you for now, I can get this in production today. Let me know what the alt text should be, and if you want it to be linked to a URL.

**Comment by marleen-linares** [comment]
Thanks Joe. I think this works just fine. I've attached a slightly larger version to use. There's no hurry on this so whenever's convenient for you. 
![simon-logo-thumb](https://user-images.githubusercontent.com/29282775/29180850-b032e418-7dbe-11e7-9689-d03e8c56dfec.png)

**Comment by joewhitsitt** [comment]
This is done. I used "Award for Campus Internationalization - NAFSA" for the alt text. no link.

Let me know about any issues.

**Comment by marleen-linares** [comment]
Thanks Joe! Would you mind linking it to this article when you get a chance?

https://international.uiowa.edu/news/ui-receives-prestigious-award-campus-internationalization

**Comment by joewhitsitt** [comment]
No problem. It should now be linked.
