### ISSUE TITLE
Link to Deleted PDF

### ISSUE THREAD

**Issue by marleen-linares** [ITS-UofIowa/international.uiowa.edu#24]
A colleague recently searched for the UI org chart in Google and came across this link in the search results: https://international.uiowa.edu/sites/international.uiowa.edu/files/oz-archive/ui-leadership-org-chart.pdf. This org chart is very out of date and needs to be removed. I've gone ahead and deleted it from our website files but the link still works. Is this just a cache issue that will remedy itself or is there something else I should do?

Thanks,
Marleen

**Comment by joewhitsitt** [comment]
@marleen-linares i get a page not found so i assume it is a cache issue.

**Comment by marleen-linares** [comment]
Okay great, just wanted to double check. Thanks Joe!
