### ISSUE TITLE
Webform Submissions Inaccessible

### ISSUE THREAD

**Issue by marleen-linares** [ITS-UofIowa/international.uiowa.edu#45]
Hey Joe,

I'm not sure if you're aware but the webform submissions on the IP site (the live one) are inaccessible. You can access the submissions from the direct link in the notification email but keep getting an error message when trying to access them from the form itself. We first noticed it yesterday.

Marleen

**Comment by joewhitsitt** [comment]
We haven't seen that before, but a site-wide cache clear seems to have resolved the issue for me. Let me know if this continues for you and/or your editors.

**Comment by marleen-linares** [comment]
Thanks Joe, that worked.
