### ISSUE TITLE
Styling Issues with Form

### ISSUE THREAD

**Issue by marleen-linares** [ITS-UofIowa/international.uiowa.edu#46]
Hey Joe. I just noticed one of our forms looks a little funny so wanted to alert you to it. In the screenshot, you can see two issues. 1)The top field label ("First Name") seems to be a little too spaced from the actual field and 2) When the "For UI Alumni" section is collapsed, it overlaps a bit with the following label.

<img width="1071" alt="screen shot 2018-09-11 at 11 58 29 am" src="https://user-images.githubusercontent.com/29282775/45375423-88e42e00-b5ba-11e8-9b49-df334d068b29.png">

**Comment by joewhitsitt** [comment]
@marleen-linares thanks for your patience, I have been on a trip and this issue queue is currently only monitored by me. I believe I have resolved the issue.

https://github.com/ITS-UofIowa/international.uiowa.edu/commit/728e94306e2dcff21755ef4eb9347d41b65717c9

**Comment by marleen-linares** [comment]
Thanks Joe!

Sent from my iPhone

On Sep 17, 2018, at 3:57 PM, Joe Whitsitt <notifications@github.com<mailto:notifications@github.com>> wrote:


@marleen-linares<https://github.com/marleen-linares> thanks for your patience, I have been on a trip and this issue queue is currently only monitored by me. I believe I have resolved the issue.

728e943<https://github.com/ITS-UofIowa/international.uiowa.edu/commit/728e94306e2dcff21755ef4eb9347d41b65717c9>
